#!/bin/zsh

## check arguments
if [[ -z $1 || -z $2 ]]; then
    echo "error: must need 2 argument"  1>&2
    exit 1
fi

## check dir
if ! [ -e ~/.schemes-setting ]; then
    touch ~/.schemes-setting
    echo 'make .schemes-setting file'
else
    echo 'already exists .schemes-setting file'
fi

if ! [ -e ~/.schemes-house ]; then
    mkdir ~/.schemes-house
    echo 'make .schemes-setting dir'
else 
    echo 'already exists .schemes-house dir'
fi
