#!/bin/zsh


## check peco

SCHEME_HOUSE_DIR=$HOME/.schemes-house
SCHEME_SETTING=$HOME/.schemes-setting

## check dir exists
if ! [ -e $SCHEME_HOUSE_DIR ]; then
    touch $SCHEME_HOUSE_DIR
    echo 'make .schemes-setting file'
else
    echo 'already exists .schemes-setting file'
fi

if ! [ -e $SCHEME_SETTING ]; then
    mkdir $SCHEME_SETTING
    echo 'make .schemes-setting dir'
else
    echo 'already exists .schemes-house dir'
fi

## get exists .terminal and peco
result=`find $SCHEME_HOUSE_DIR -name '*.terminal' | peco`

TERM_PROFILE=$result
# echo $TERM_PROFILE
CURRENT_PROFILE="$(defaults read com.apple.Terminal 'Default Window Settings')"
echo $CURRENT_PROFILE
FILE_NAME_EXT=${result##**/}
FILE_NAME=${FILE_NAME_EXT%.*}

## むう。挙動がよくわからんねぇ。変なschemeがデフォルトにセットされたりしておる
if [ "${CURRENT_PROFILE}" != "${TERM_PROFILE}" ]; then
    open "$TERM_PROFILE"
#     defaults write com.apple.Terminal "Default Window Settings" -string "$FILE_NAME"
#     defaults write com.apple.Terminal "Startup Window Settings" -string "$FILE_NAME"
fi

function set_font
{
    osascript -e "tell application \"Terminal\" to set the font name of window 1 to \"$1\""
    osascript -e "tell application \"Terminal\" to set the font size of window 1 to $2"
}

set_font "Menleo" 12
