#!/bin/zsh

## check arguments
if [[ -z $1 || -z $2 ]]; then
    echo "error: must need 2 argument"  1>&2
    exit 1
fi

## check dir
if ! [ -e ~/.schemes-setting ]; then
    touch ~/.schemes-setting
    echo 'make .schemes-setting file'
else
    echo 'already exists .schemes-setting file'
fi

if ! [ -e ~/.schemes-house ]; then
    mkdir ~/.schemes-house
    echo 'make .schemes-setting dir'
else 
    echo 'already exists .schemes-house dir'
fi
function set_font
{
    osascript -e "tell application \"Terminal\" to set the font name of window 1 to \"$1\""
    osascript -e "tell application \"Terminal\" to set the font size of window 1 to $2"
}

set_font "Menleo" 12
