#!/bin/bash

# define variables
SCHEME_HOUSE_DIR=$HOME/.schemes-house
SCHEME_SETTING=$HOME/.schemes-setting

open_scheme()
{
    result=`find $SCHEME_HOUSE_DIR -name '*.terminal' | peco`
    open $result
}

get_scheme()
{
    echo -n "PLZ type \"username/reponame\" in github. "
    read userNameAndRepoName
    userName=`echo $userNameAndRepoName | awk -F / '{print $1}'`
    repoName=`echo $userNameAndRepoName | awk -F / '{print $2}'`
    uri="https://github.com/${userNameAndRepoName}.git"
    git clone "${uri}" "${SCHEME_HOUSE_DIR}/${userName}/${repoName}"
}

save_scheme()
{
    selected=`defaults read com.apple.Terminal 'Window Settings' | grep name | tr -d ' ' | sed -e 's/name=//' | sed -e 's/;//' | peco`
    defaults write com.apple.Terminal "Default Window Settings" -string $selected
    defaults write com.apple.Terminal "Startup Window Settings" -string $selected
    echo "set ${selected}. PLZ restart terminal"
}

load_list()
{
    echo "----- schemes list -----"
    defaults read com.apple.Terminal 'Window Settings' | grep name | tr -d ' ' | sed -e 's/name=//' 
}

set_font_name()
{
    selected=`fc-list --verbose | grep family: | sed -e 's/family://' | sed -e 's/(s)//' | peco`
    osascript -e "tell application \"Terminal\" to set the font name of window 1 to $selected"
    echo "DONE"
}

set_font_size()
{
    echo -n "font size? " 
    read size
    osascript -e "tell application \"Terminal\" to set the font size of window 1 to $size"
    echo "DONE"
}

horsetail()
{
    ## check dir exists
    if ! [ -e $SCHEME_HOUSE_DIR ]; then
        touch $SCHEME_HOUSE_DIR
        echo 'make .schemes-setting file'
    fi

    if ! [ -e $SCHEME_SETTING ]; then
        mkdir $SCHEME_SETTING
        echo 'make .schemes-setting dir'
    fi

    ## select function
    COMMANDS=("open" "get" "save" "list" "font_name" "font_size")
    SELECTED_COMMAND=`for item in ${COMMANDS[@]}; do echo $item; done | peco`
    if [ $SELECTED_COMMAND = "open" ]; then
        open_scheme
    elif [ $SELECTED_COMMAND = "get" ]; then
        get_scheme
    elif [ $SELECTED_COMMAND = "save" ]; then
        save_scheme
    elif [ $SELECTED_COMMAND = "list" ]; then
        load_list
    elif [ $SELECTED_COMMAND = "font_name" ]; then
        set_font_name
    elif [ $SELECTED_COMMAND = "font_size" ]; then
        set_font_size
    fi
}
